project_id = "jcvxklzcxngctyqmknax"

[functions.log-download]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.get-download-stats]
verify_jwt = false

[functions.customer-service-chat]
verify_jwt = false

[functions.check-aurora-alerts]
verify_jwt = false

[functions.send-aurora-confirmation]
verify_jwt = false

[functions.unsubscribe-aurora]
verify_jwt = false

[functions.beds24-availability]
verify_jwt = false

[functions.admin-settings]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.send-admin-invite]
verify_jwt = false

[functions.melcloud-api]
verify_jwt = false

[functions.melcloud-cron]
verify_jwt = false

[functions.maintenance-bookings]
verify_jwt = false

[functions.send-worklist]
verify_jwt = false

[functions.maintenance-settings]
verify_jwt = false

[functions.mark-cleaned]
verify_jwt = false

[functions.get-cleaning-status]
verify_jwt = false

[functions.homey-callback]
verify_jwt = false

[functions.homey-api]
verify_jwt = false

[functions.floor-heating-cron]
verify_jwt = false

[functions.fmi-snow-data]
verify_jwt = false
