// AUTO-COPIED from src/data/sitemapRoutes.ts (edge runtime cannot import src/)
// AUTO-DERIVED from src/App.tsx — single source of truth for the sitemap.
// Keep in sync when routes change (see scripts/sync-sitemap-routes.md).
//
// EXCLUDED BY DESIGN — these render <Majoitukset /> and emit a canonical
// tag pointing to /majoitukset. Do not add them to the sitemap:
// /majoitus, /majoitus-levi, /loma-asunto-levi, /huoneisto-levi,
// /vuokra-asunto-levi, /levi-majoitus-keskusta
//
// Also excluded: redirect (<Navigate/>) routes, wildcard/param routes,
// /admin*, /unsubscribe, /tiketti-ratkaistu.

export type SitemapLang = "fi" | "en" | "sv" | "de" | "fr" | "es" | "nl";

export type SitemapRoute = {
  path: string;
  lang: SitemapLang;
  priority: number;
  changefreq: "daily" | "weekly" | "monthly" | "yearly";
  altGroup?: string; // shared key linking language variants of one page
};

export const SITEMAP_ROUTES: SitemapRoute[] = [
  { path: "/", lang: "fi", priority: 1.0, changefreq: "weekly" },
  { path: "/majoitukset", lang: "fi", priority: 0.9, changefreq: "weekly" },
  { path: "/en/apartment-levi", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/ski-in-ski-out-levi", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/mokit-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "mokit-levilla" },
  { path: "/vuokramokit/hiihtajankuja-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "hub-hiihtajankuja-levi" },
  { path: "/vuokramokit/skimbaajankuja-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "hub-skimbaajankuja-levi" },
  { path: "/vuokramokit/glacier-apartments-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "hub-glacier-apartments-levi" },
  { path: "/vuokramokit/postintie-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "hub-postintie-levi" },
  { path: "/vuokramokit/hiihtajankuja-2-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "hub-hiihtajankuja-2-levi" },
  { path: "/vuokramokit/skimbaajankuja-4-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "hub-skimbaajankuja-4-levi" },
  { path: "/vuokramokit/leviraitti-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "hub-leviraitti-levi" },
  { path: "/en/log-cabins-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "mokit-levilla" },
  { path: "/majoitus/levin-keskustahuoneistot", lang: "fi", priority: 0.6, changefreq: "monthly" },
  { path: "/opas/autolla-ajaminen-lapissa", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-autolla-ajaminen-lapissa" },
  { path: "/ajankohtaista", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "ajankohtaista" },
  { path: "/levi", lang: "fi", priority: 0.8, changefreq: "monthly", altGroup: "levi" },
  { path: "/levi/joulu-lapissa", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/joulu", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/xmas", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/levi/saatieto-levilta", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "levi-saatieto-levilta" },
  { path: "/lumitilanne", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "lumitilanne" },
  { path: "/revontulet", lang: "fi", priority: 0.8, changefreq: "monthly", altGroup: "revontulet" },
  { path: "/yhteystiedot", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "yhteystiedot" },
  { path: "/ukk", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "ukk" },
  { path: "/varausehdot", lang: "fi", priority: 0.3, changefreq: "yearly", altGroup: "varausehdot" },
  { path: "/tietosuoja", lang: "fi", priority: 0.3, changefreq: "yearly", altGroup: "tietosuoja" },
  { path: "/yritys", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "yritys" },
  { path: "/tietovisa", lang: "fi", priority: 0.5, changefreq: "monthly", altGroup: "tietovisa" },
  { path: "/akkilahdot", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "akkilahdot" },
  { path: "/en", lang: "en", priority: 1.0, changefreq: "weekly" },
  { path: "/en/accommodations", lang: "en", priority: 0.9, changefreq: "weekly" },
  { path: "/en/news", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "ajankohtaista" },
  { path: "/en/levi", lang: "en", priority: 0.8, changefreq: "monthly", altGroup: "levi" },
  { path: "/en/levi/christmas-in-lapland", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/levi/weather-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "levi-saatieto-levilta" },
  { path: "/en/snowreport", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "lumitilanne" },
  { path: "/en/northern-lights", lang: "en", priority: 0.8, changefreq: "monthly", altGroup: "revontulet" },
  { path: "/en/contact", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "yhteystiedot" },
  { path: "/en/faq", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "ukk" },
  { path: "/en/company", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "yritys" },
  { path: "/en/quiz", lang: "en", priority: 0.5, changefreq: "monthly", altGroup: "tietovisa" },
  { path: "/en/last-minute", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "akkilahdot" },
  { path: "/en/booking-terms", lang: "en", priority: 0.3, changefreq: "yearly", altGroup: "varausehdot" },
  { path: "/en/privacy", lang: "en", priority: 0.3, changefreq: "yearly", altGroup: "tietosuoja" },
  { path: "/sv/boende", lang: "sv", priority: 0.7, changefreq: "monthly" },
  { path: "/sv/nyheter", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "ajankohtaista" },
  { path: "/sv/levi", lang: "sv", priority: 0.8, changefreq: "monthly", altGroup: "levi" },
  { path: "/sv/levi/jul-i-lappland", lang: "sv", priority: 0.7, changefreq: "monthly" },
  { path: "/sv/norrsken", lang: "sv", priority: 0.8, changefreq: "monthly", altGroup: "revontulet" },
  { path: "/sv/kontakt", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "yhteystiedot" },
  { path: "/sv/faq", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "ukk" },
  { path: "/sv/foretag", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "yritys" },
  { path: "/sv/quiz", lang: "sv", priority: 0.5, changefreq: "monthly", altGroup: "tietovisa" },
  { path: "/sv/sista-minuten", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "akkilahdot" },
  { path: "/sv/bokningsvillkor", lang: "sv", priority: 0.3, changefreq: "yearly", altGroup: "varausehdot" },
  { path: "/sv/integritetspolicy", lang: "sv", priority: 0.3, changefreq: "yearly", altGroup: "tietosuoja" },
  { path: "/de/unterkuenfte", lang: "de", priority: 0.7, changefreq: "monthly" },
  { path: "/de/aktuelles", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "ajankohtaista" },
  { path: "/de/levi", lang: "de", priority: 0.8, changefreq: "monthly", altGroup: "levi" },
  { path: "/de/levi/weihnachten-in-lappland", lang: "de", priority: 0.7, changefreq: "monthly" },
  { path: "/de/nordlichter", lang: "de", priority: 0.8, changefreq: "monthly", altGroup: "revontulet" },
  { path: "/de/kontakt", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "yhteystiedot" },
  { path: "/de/faq", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "ukk" },
  { path: "/de/unternehmen", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "yritys" },
  { path: "/de/quiz", lang: "de", priority: 0.5, changefreq: "monthly", altGroup: "tietovisa" },
  { path: "/de/last-minute", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "akkilahdot" },
  { path: "/de/buchungsbedingungen", lang: "de", priority: 0.3, changefreq: "yearly", altGroup: "varausehdot" },
  { path: "/de/datenschutz", lang: "de", priority: 0.3, changefreq: "yearly", altGroup: "tietosuoja" },
  { path: "/es/alojamientos", lang: "es", priority: 0.7, changefreq: "monthly" },
  { path: "/es/noticias", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "ajankohtaista" },
  { path: "/es/levi", lang: "es", priority: 0.8, changefreq: "monthly", altGroup: "levi" },
  { path: "/es/levi/navidad-en-laponia", lang: "es", priority: 0.7, changefreq: "monthly" },
  { path: "/es/auroras-boreales", lang: "es", priority: 0.8, changefreq: "monthly", altGroup: "revontulet" },
  { path: "/es/contacto", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "yhteystiedot" },
  { path: "/es/preguntas-frecuentes", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "ukk" },
  { path: "/es/empresa", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "yritys" },
  { path: "/es/quiz", lang: "es", priority: 0.5, changefreq: "monthly", altGroup: "tietovisa" },
  { path: "/es/ultima-hora", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "akkilahdot" },
  { path: "/es/terminos-de-reserva", lang: "es", priority: 0.3, changefreq: "yearly", altGroup: "varausehdot" },
  { path: "/es/privacidad", lang: "es", priority: 0.3, changefreq: "yearly", altGroup: "tietosuoja" },
  { path: "/fr/hebergements", lang: "fr", priority: 0.7, changefreq: "monthly" },
  { path: "/fr/actualites", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "ajankohtaista" },
  { path: "/fr/levi", lang: "fr", priority: 0.8, changefreq: "monthly", altGroup: "levi" },
  { path: "/fr/levi/noel-en-laponie", lang: "fr", priority: 0.7, changefreq: "monthly" },
  { path: "/fr/aurores-boreales", lang: "fr", priority: 0.8, changefreq: "monthly", altGroup: "revontulet" },
  { path: "/fr/contact", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "yhteystiedot" },
  { path: "/fr/faq", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "ukk" },
  { path: "/fr/entreprise", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "yritys" },
  { path: "/fr/quiz", lang: "fr", priority: 0.5, changefreq: "monthly", altGroup: "tietovisa" },
  { path: "/fr/derniere-minute", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "akkilahdot" },
  { path: "/fr/conditions-de-reservation", lang: "fr", priority: 0.3, changefreq: "yearly", altGroup: "varausehdot" },
  { path: "/fr/confidentialite", lang: "fr", priority: 0.3, changefreq: "yearly", altGroup: "tietosuoja" },
  { path: "/nl/accommodaties", lang: "nl", priority: 0.7, changefreq: "monthly" },
  { path: "/nl/nieuws", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "ajankohtaista" },
  { path: "/nl/levi", lang: "nl", priority: 0.8, changefreq: "monthly", altGroup: "levi" },
  { path: "/nl/levi/kerst-in-lapland", lang: "nl", priority: 0.7, changefreq: "monthly" },
  { path: "/nl/noorderlicht", lang: "nl", priority: 0.8, changefreq: "monthly", altGroup: "revontulet" },
  { path: "/nl/contact", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "yhteystiedot" },
  { path: "/nl/faq", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "ukk" },
  { path: "/nl/bedrijf", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "yritys" },
  { path: "/nl/quiz", lang: "nl", priority: 0.5, changefreq: "monthly", altGroup: "tietovisa" },
  { path: "/nl/last-minute", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "akkilahdot" },
  { path: "/nl/boekingsvoorwaarden", lang: "nl", priority: 0.3, changefreq: "yearly", altGroup: "varausehdot" },
  { path: "/nl/privacy", lang: "nl", priority: 0.3, changefreq: "yearly", altGroup: "tietosuoja" },
  { path: "/nl/gids/skieen-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-laskettelu-levi" },
  { path: "/nl/gids/seizoenen-in-levi", lang: "nl", priority: 0.8, changefreq: "monthly", altGroup: "opas-vuodenajat-levi" },
  { path: "/nl/gids/activiteiten-in-levi", lang: "nl", priority: 0.8, changefreq: "monthly", altGroup: "opas-aktiviteetit-levi" },
  { path: "/nl/gids/reisgids-levi", lang: "nl", priority: 0.8, changefreq: "monthly", altGroup: "opas-matkaopas-levi" },
  { path: "/nl/gids/waarom-levi-kiezen", lang: "nl", priority: 0.8, changefreq: "monthly", altGroup: "opas-miksi-valita-levi" },
  { path: "/nl/gids/winterkleding-levi-lapland", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-talvivarusteet-leville" },
  { path: "/nl/gids/hoe-kom-je-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "matka-miten-paasee-leville-helsingista" },
  { path: "/nl/activiteiten/winteractiviteiten-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-parhaat-talviaktiviteetit-levi" },
  { path: "/nl/activiteiten/husky-safari-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-koiravaljakkoajelu-levi" },
  { path: "/nl/gids/langlaufen-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-hiihtoladut-levi" },
  { path: "/nl/gids/levi-met-kinderen", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-lapsiperheet-levilla" },
  { path: "/nl/gids/prijzen-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly" },
  { path: "/nl/levi/weer-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "levi-saatieto-levilta" },
  { path: "/nl/gids/winter-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-talvi-levi" },
  { path: "/nl/gids/lente-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevat-levi" },
  { path: "/nl/gids/zomer-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-kesa-levi" },
  { path: "/nl/gids/herfst-ruska-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-syksy-ruska-levi" },
  { path: "/nl/activiteiten/sneeuwscooter-safari-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-moottorikelkkasafari-vinkit-levi" },
  { path: "/nl/gids/vervoer-in-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-liikkuminen-levilla" },
  { path: "/opas/vuodenajat-levi", lang: "fi", priority: 0.8, changefreq: "monthly", altGroup: "opas-vuodenajat-levi" },
  { path: "/opas/aktiviteetit-levi", lang: "fi", priority: 0.8, changefreq: "monthly", altGroup: "opas-aktiviteetit-levi" },
  { path: "/opas/matkaopas-levi", lang: "fi", priority: 0.8, changefreq: "monthly", altGroup: "opas-matkaopas-levi" },
  { path: "/opas/miksi-valita-levi", lang: "fi", priority: 0.8, changefreq: "monthly", altGroup: "opas-miksi-valita-levi" },
  { path: "/guide/seasons-in-levi", lang: "en", priority: 0.8, changefreq: "monthly", altGroup: "opas-vuodenajat-levi" },
  { path: "/guide/activities-in-levi", lang: "en", priority: 0.8, changefreq: "monthly", altGroup: "opas-aktiviteetit-levi" },
  { path: "/guide/travel-to-levi", lang: "en", priority: 0.8, changefreq: "monthly", altGroup: "opas-matkaopas-levi" },
  { path: "/guide/why-choose-levi", lang: "en", priority: 0.8, changefreq: "monthly", altGroup: "opas-miksi-valita-levi" },
  { path: "/de/ratgeber/jahreszeiten-in-levi", lang: "de", priority: 0.8, changefreq: "monthly", altGroup: "opas-vuodenajat-levi" },
  { path: "/sv/guide/arstilder-i-levi", lang: "sv", priority: 0.8, changefreq: "monthly", altGroup: "opas-vuodenajat-levi" },
  { path: "/fr/guide/saisons-a-levi", lang: "fr", priority: 0.8, changefreq: "monthly", altGroup: "opas-vuodenajat-levi" },
  { path: "/es/guia/estaciones-en-levi", lang: "es", priority: 0.8, changefreq: "monthly", altGroup: "opas-vuodenajat-levi" },
  { path: "/de/ratgeber/aktivitaeten-in-levi", lang: "de", priority: 0.8, changefreq: "monthly", altGroup: "opas-aktiviteetit-levi" },
  { path: "/sv/guide/aktiviteter-i-levi", lang: "sv", priority: 0.8, changefreq: "monthly", altGroup: "opas-aktiviteetit-levi" },
  { path: "/fr/guide/activites-a-levi", lang: "fr", priority: 0.8, changefreq: "monthly", altGroup: "opas-aktiviteetit-levi" },
  { path: "/es/guia/actividades-en-levi", lang: "es", priority: 0.8, changefreq: "monthly", altGroup: "opas-aktiviteetit-levi" },
  { path: "/opas/talvivarusteet-leville", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-talvivarusteet-leville" },
  { path: "/opas/laskettelu-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-laskettelu-levi" },
  { path: "/opas/world-cup-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "world-cup-levi" },
  { path: "/opas/kaamos-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "kaamos-levi" },
  { path: "/guide/polar-night-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "kaamos-levi" },
  { path: "/opas/levi-3-paivassa", lang: "fi", priority: 0.8, changefreq: "monthly", altGroup: "levi-3-days" },
  { path: "/guide/levi-in-3-days", lang: "en", priority: 0.8, changefreq: "monthly", altGroup: "levi-3-days" },
  { path: "/guide/levi-world-cup", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "world-cup-levi" },
  { path: "/opas/hiihtoladut-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-hiihtoladut-levi" },
  { path: "/opas/talvi-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-talvi-levi" },
  { path: "/opas/kevat-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevat-levi" },
  { path: "/opas/kesa-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-kesa-levi" },
  { path: "/opas/syksy-ruska-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-syksy-ruska-levi" },
  { path: "/opas/paras-aika-matkustaa-leville", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/aktiviteetit/moottorikelkkasafari-vinkit-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-moottorikelkkasafari-vinkit-levi" },
  { path: "/aktiviteetit/koiravaljakkoajelu-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-koiravaljakkoajelu-levi" },
  { path: "/aktiviteetit/vaellus-ja-maastopyoraily-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-vaellus-ja-maastopyoraily-levi" },
  { path: "/matka/miten-paasee-leville-helsingista", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "matka-miten-paasee-leville-helsingista" },
  { path: "/aktiviteetit/parhaat-talviaktiviteetit-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-parhaat-talviaktiviteetit-levi" },
  { path: "/aktiviteetit/porosafari-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-porosafari-levi" },
  { path: "/guide/how-to-dress-for-winter-in-levi-lapland", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-talvivarusteet-leville" },
  { path: "/guide/skiing-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-laskettelu-levi" },
  { path: "/guide/cross-country-skiing-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-hiihtoladut-levi" },
  { path: "/guide/winter-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-talvi-levi" },
  { path: "/guide/spring-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevat-levi" },
  { path: "/guide/summer-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-kesa-levi" },
  { path: "/guide/autumn-ruska-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-syksy-ruska-levi" },
  { path: "/guide/best-time-to-visit-levi", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/activities/snowmobile-safari-tips-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-moottorikelkkasafari-vinkit-levi" },
  { path: "/activities/husky-safari-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-koiravaljakkoajelu-levi" },
  { path: "/activities/hiking-and-biking-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-vaellus-ja-maastopyoraily-levi" },
  { path: "/travel/how-to-get-to-levi-from-helsinki-and-abroad", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "matka-miten-paasee-leville-helsingista" },
  { path: "/activities/top-winter-activities-in-levi-lapland", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-parhaat-talviaktiviteetit-levi" },
  { path: "/activities/reindeer-safari-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-porosafari-levi" },
  { path: "/opas/liikkuminen-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-liikkuminen-levilla" },
  { path: "/opas/ravintolat-ja-palvelut-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-ravintolat-ja-palvelut-levilla" },
  { path: "/opas/levin-ravintolat-ja-annokset", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-levin-ravintolat-ja-annokset" },
  { path: "/opas/lapsiperheet-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-lapsiperheet-levilla" },
  { path: "/opas/levi-ilman-autoa", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-levi-ilman-autoa" },
  { path: "/opas/lammitysjarjestelmat-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-lammitysjarjestelmat-levi" },
  { path: "/opas/levi-vs-yllas-vs-ruka", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/opas/levi-vs-rovaniemi", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/opas/levi-vs-saariselka", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/opas/sauna-levilla", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/opas/levin-alueet", lang: "fi", priority: 0.8, changefreq: "monthly", altGroup: "opas-levin-alueet" },
  { path: "/guide/levi-areas", lang: "en", priority: 0.8, changefreq: "monthly", altGroup: "opas-levin-alueet" },
  { path: "/opas/majoitus-levilla", lang: "fi", priority: 0.6, changefreq: "monthly" },
  { path: "/opas/vuokramokit-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-vuokramokit-levi" },
  { path: "/en/guides/cabins-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-vuokramokit-levi" },
  { path: "/levi/ukk", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "levi-ukk" },
  { path: "/opas/lapin-sanasto", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-lapin-sanasto" },
  { path: "/opas/hinnat-levilla", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/opas/vappu-levilla", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/guide/getting-around-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-liikkuminen-levilla" },
  { path: "/guide/driving-in-lapland", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-autolla-ajaminen-lapissa" },
  { path: "/guide/restaurants-and-services-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-ravintolat-ja-palvelut-levilla" },
  { path: "/guide/levi-restaurants-and-dishes", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-levin-ravintolat-ja-annokset" },
  { path: "/guide/levi-with-children", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-lapsiperheet-levilla" },
  { path: "/guide/levi-without-a-car", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-levi-ilman-autoa" },
  { path: "/guide/heating-systems-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-lammitysjarjestelmat-levi" },
  { path: "/guide/levi-vs-yllas-vs-ruka-comparison", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-yllas-vs-ruka-comparison" },
  { path: "/guide/levi-vs-rovaniemi-comparison", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-rovaniemi-comparison" },
  { path: "/guide/levi-vs-saariselka-comparison", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/guide/lapland-glossary", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-lapin-sanasto" },
  { path: "/guide/prices-in-levi", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/nl/gids/levi-vs-yllas-vs-ruka", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-yllas-vs-ruka-comparison" },
  { path: "/nl/gids/levi-vs-rovaniemi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-rovaniemi-comparison" },
  { path: "/de/guide/levi-vs-yllas-vs-ruka", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-yllas-vs-ruka-comparison" },
  { path: "/de/guide/levi-vs-rovaniemi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-rovaniemi-comparison" },
  { path: "/fr/guide/levi-vs-yllas-vs-ruka", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-yllas-vs-ruka-comparison" },
  { path: "/fr/guide/levi-vs-rovaniemi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-rovaniemi-comparison" },
  { path: "/es/guia/levi-vs-yllas-vs-ruka", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-yllas-vs-ruka-comparison" },
  { path: "/es/guia/levi-vs-rovaniemi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "guide-levi-vs-rovaniemi-comparison" },
  { path: "/sv/guide/why-choose-levi", lang: "sv", priority: 0.8, changefreq: "monthly", altGroup: "opas-miksi-valita-levi" },
  { path: "/de/guide/why-choose-levi", lang: "de", priority: 0.8, changefreq: "monthly", altGroup: "opas-miksi-valita-levi" },
  { path: "/fr/guide/why-choose-levi", lang: "fr", priority: 0.8, changefreq: "monthly", altGroup: "opas-miksi-valita-levi" },
  { path: "/es/guia/why-choose-levi", lang: "es", priority: 0.8, changefreq: "monthly", altGroup: "opas-miksi-valita-levi" },
  { path: "/guide/finnish-sauna-in-levi", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/opas/ulkoporeallas-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-ulkoporeallas-levilla" },
  { path: "/guide/outdoor-hot-tub-levi-cabin", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-ulkoporeallas-levilla" },
  { path: "/en/guide/christmas-dinner-in-levi", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/lomasuunnittelija", lang: "fi", priority: 0.5, changefreq: "monthly", altGroup: "lomasuunnittelija" },
  { path: "/en/holiday-planner", lang: "en", priority: 0.5, changefreq: "monthly", altGroup: "lomasuunnittelija" },
  { path: "/en/apartments", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/apartments/studio", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/apartments/for-4", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/apartments/for-6", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/apartments/for-8", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/apartments/large-group", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/apartments/penthouse", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/apartments/2-bedroom", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/apartments/3-bedroom", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/en/apartments/levi-center", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/asiakaspalvelu", lang: "fi", priority: 0.5, changefreq: "monthly", altGroup: "asiakaspalvelu" },
  { path: "/en/support", lang: "en", priority: 0.5, changefreq: "monthly", altGroup: "asiakaspalvelu" },
  { path: "/levi-pronounce", lang: "fi", priority: 0.5, changefreq: "monthly" },
  { path: "/latuinfo", lang: "fi", priority: 0.5, changefreq: "monthly" },
  { path: "/myy-loma-asuntosi", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/seuratuki", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/en/club-support", lang: "en", priority: 0.7, changefreq: "monthly" },
  { path: "/accommodations/guides/bearlodge", lang: "fi", priority: 0.5, changefreq: "monthly" },
  { path: "/majoitukset/oppaat/bearlodge", lang: "fi", priority: 0.9, changefreq: "weekly" },
  { path: "/majoitukset/oppaat/karhupirtti", lang: "fi", priority: 0.9, changefreq: "weekly" },
  { path: "/accommodations/guides/skistar-apartments", lang: "fi", priority: 0.5, changefreq: "monthly" },
  { path: "/majoitukset/oppaat/skistar-huoneistot", lang: "fi", priority: 0.9, changefreq: "weekly" },
  { path: "/accommodations/guides/frontslope-apartments", lang: "fi", priority: 0.5, changefreq: "monthly" },
  { path: "/takka-ohje", lang: "fi", priority: 0.5, changefreq: "monthly", altGroup: "takka-ohje" },
  { path: "/en/fireplace", lang: "en", priority: 0.5, changefreq: "monthly", altGroup: "takka-ohje" },
  { path: "/opas/paras-aika-revontulet-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-paras-aika-revontulet-levi" },
  { path: "/opas/revontulisesonki-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulisesonki-levi" },
  { path: "/opas/revontuliennuste-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontuliennuste-levi" },
  { path: "/opas/missa-nahda-revontulet-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-missa-nahda-revontulet-levi" },
  { path: "/opas/revontulien-valokuvaus-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-valokuvaus-levi" },
  { path: "/opas/miten-revontulet-syntyvat", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-miten-revontulet-syntyvat" },
  { path: "/opas/revontulien-varit", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-varit" },
  { path: "/guide/best-time-to-see-northern-lights-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-paras-aika-revontulet-levi" },
  { path: "/guide/northern-lights-season-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulisesonki-levi" },
  { path: "/guide/northern-lights-forecast-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontuliennuste-levi" },
  { path: "/guide/where-to-see-northern-lights-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-missa-nahda-revontulet-levi" },
  { path: "/guide/northern-lights-photography-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-valokuvaus-levi" },
  { path: "/guide/how-northern-lights-form", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-miten-revontulet-syntyvat" },
  { path: "/guide/northern-lights-colors-explained", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-varit" },
  { path: "/opas/joulupukki-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-joulupukki-levilla" },
  { path: "/opas/pakkauslista-lapin-lomalle", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-pakkauslista-lapin-lomalle" },
  { path: "/opas/afterski-ja-yoelama-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-afterski-ja-yoelama-levilla" },
  { path: "/aktiviteetit/melonta-ja-sup-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-melonta-ja-sup-levi" },
  { path: "/activities/levi-for-kids", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-levi-lapsille" },
  { path: "/activities/canoeing-and-sup-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-melonta-ja-sup-levi" },
  { path: "/opas/paras-aika-vierailla-levilla", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/levi-map", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/de/ratgeber/beste-zeit-nordlichter-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "opas-paras-aika-revontulet-levi" },
  { path: "/sv/guide/basta-tiden-norrsken-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "opas-paras-aika-revontulet-levi" },
  { path: "/es/guia/mejor-momento-auroras-boreales-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "opas-paras-aika-revontulet-levi" },
  { path: "/fr/guide/meilleur-moment-aurores-boreales-levi", lang: "fr", priority: 0.6, changefreq: "monthly" },
  { path: "/nl/gids/beste-tijd-noorderlicht-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-paras-aika-revontulet-levi" },
  { path: "/de/ratgeber/nordlichter-saison-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulisesonki-levi" },
  { path: "/sv/guide/norrsken-sasong-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulisesonki-levi" },
  { path: "/es/guia/temporada-auroras-boreales-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulisesonki-levi" },
  { path: "/fr/guide/saison-aurores-boreales-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulisesonki-levi" },
  { path: "/nl/gids/noorderlicht-seizoen-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulisesonki-levi" },
  { path: "/de/ratgeber/nordlichter-vorhersage-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontuliennuste-levi" },
  { path: "/sv/guide/norrsken-prognos-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontuliennuste-levi" },
  { path: "/es/guia/prevision-auroras-boreales-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontuliennuste-levi" },
  { path: "/fr/guide/prevision-aurores-boreales-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontuliennuste-levi" },
  { path: "/nl/gids/noorderlicht-verwachting-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontuliennuste-levi" },
  { path: "/de/ratgeber/wo-nordlichter-sehen-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "opas-missa-nahda-revontulet-levi" },
  { path: "/sv/guide/var-se-norrsken-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "opas-missa-nahda-revontulet-levi" },
  { path: "/es/guia/donde-ver-auroras-boreales-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "opas-missa-nahda-revontulet-levi" },
  { path: "/fr/guide/ou-voir-aurores-boreales-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "opas-missa-nahda-revontulet-levi" },
  { path: "/nl/gids/waar-noorderlicht-zien-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-missa-nahda-revontulet-levi" },
  { path: "/de/ratgeber/nordlichter-fotografieren-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-valokuvaus-levi" },
  { path: "/sv/guide/fotografera-norrsken-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-valokuvaus-levi" },
  { path: "/es/guia/fotografiar-auroras-boreales-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-valokuvaus-levi" },
  { path: "/fr/guide/photographier-aurores-boreales-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-valokuvaus-levi" },
  { path: "/nl/gids/noorderlicht-fotograferen-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-valokuvaus-levi" },
  { path: "/de/ratgeber/wie-entstehen-nordlichter", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "opas-miten-revontulet-syntyvat" },
  { path: "/sv/guide/hur-uppstar-norrsken", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "opas-miten-revontulet-syntyvat" },
  { path: "/es/guia/como-se-forman-auroras-boreales", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "opas-miten-revontulet-syntyvat" },
  { path: "/fr/guide/comment-se-forment-aurores-boreales", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "opas-miten-revontulet-syntyvat" },
  { path: "/nl/gids/hoe-ontstaat-noorderlicht", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-miten-revontulet-syntyvat" },
  { path: "/de/ratgeber/farben-der-nordlichter", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-varit" },
  { path: "/sv/guide/norrskens-farger", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-varit" },
  { path: "/es/guia/colores-auroras-boreales", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-varit" },
  { path: "/fr/guide/couleurs-aurores-boreales", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-varit" },
  { path: "/nl/gids/kleuren-van-noorderlicht", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-revontulien-varit" },
  { path: "/de/aktivitaeten/husky-safari-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-koiravaljakkoajelu-levi" },
  { path: "/de/aktivitaeten/schneemobil-safari-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-moottorikelkkasafari-vinkit-levi" },
  { path: "/sv/aktiviteter/husky-safari-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-koiravaljakkoajelu-levi" },
  { path: "/fr/activites/safari-husky-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-koiravaljakkoajelu-levi" },
  { path: "/es/actividades/safari-huskies-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-koiravaljakkoajelu-levi" },
  { path: "/sv/aktiviteter/snoskotersafari-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-moottorikelkkasafari-vinkit-levi" },
  { path: "/fr/activites/safari-motoneige-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-moottorikelkkasafari-vinkit-levi" },
  { path: "/es/actividades/safari-motonieve-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-moottorikelkkasafari-vinkit-levi" },
  { path: "/de/ratgeber/langlauf-in-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "opas-hiihtoladut-levi" },
  { path: "/sv/guide/langdskidakning-i-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "opas-hiihtoladut-levi" },
  { path: "/fr/guide/ski-de-fond-a-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "opas-hiihtoladut-levi" },
  { path: "/es/guia/esqui-de-fondo-en-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "opas-hiihtoladut-levi" },
  { path: "/de/aktivitaeten/winteraktivitaeten-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-parhaat-talviaktiviteetit-levi" },
  { path: "/sv/aktiviteter/vinteraktiviteter-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-parhaat-talviaktiviteetit-levi" },
  { path: "/fr/activites/activites-hiver-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-parhaat-talviaktiviteetit-levi" },
  { path: "/es/actividades/actividades-invierno-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-parhaat-talviaktiviteetit-levi" },
  { path: "/aktiviteetit/fatbike-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-fatbike-levi" },
  { path: "/activities/fatbiking-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-fatbike-levi" },
  { path: "/de/aktivitaeten/fatbike-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-fatbike-levi" },
  { path: "/sv/aktiviteter/fatbike-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-fatbike-levi" },
  { path: "/es/actividades/fatbike-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-fatbike-levi" },
  { path: "/fr/activites/fatbike-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-fatbike-levi" },
  { path: "/nl/activiteiten/fatbike-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-fatbike-levi" },
  { path: "/aktiviteetit/golf-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-golf-levi" },
  { path: "/activities/golf-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-golf-levi" },
  { path: "/aktiviteetit/ratsastus-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-ratsastus-levi" },
  { path: "/activities/horse-riding-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-ratsastus-levi" },
  { path: "/aktiviteetit/pilkkiminen-ja-kalastus-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-pilkkiminen-ja-kalastus-levi" },
  { path: "/activities/ice-fishing-and-fishing-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-pilkkiminen-ja-kalastus-levi" },
  { path: "/aktiviteetit/avantouinti-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-avantouinti-levi" },
  { path: "/activities/ice-swimming-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-avantouinti-levi" },
  { path: "/de/aktivitaeten/eisschwimmen-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-avantouinti-levi" },
  { path: "/sv/aktiviteter/vinterbad-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-avantouinti-levi" },
  { path: "/es/actividades/bano-en-hielo-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-avantouinti-levi" },
  { path: "/fr/activites/bain-glace-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-avantouinti-levi" },
  { path: "/nl/activiteiten/ijszwemmen-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-avantouinti-levi" },
  { path: "/aktiviteetit/levi-lapsille", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-levi-lapsille" },
  { path: "/aktiviteetit/lumikenkaily-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-lumikenkaily-levi" },
  { path: "/activities/snowshoeing-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-lumikenkaily-levi" },
  { path: "/de/aktivitaeten/schneeschuhwandern-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-lumikenkaily-levi" },
  { path: "/sv/aktiviteter/snoskovandrng-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-lumikenkaily-levi" },
  { path: "/es/actividades/raquetas-nieve-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-lumikenkaily-levi" },
  { path: "/fr/activites/raquettes-neige-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-lumikenkaily-levi" },
  { path: "/nl/activiteiten/sneeuwschoenwandelen-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-lumikenkaily-levi" },
  { path: "/de/aktivitaeten/rentiersafari-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-porosafari-levi" },
  { path: "/sv/aktiviteter/rensafari-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-porosafari-levi" },
  { path: "/es/actividades/safari-renos-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-porosafari-levi" },
  { path: "/fr/activites/safari-rennes-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-porosafari-levi" },
  { path: "/nl/activiteiten/rendiersafari-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "aktiviteetit-porosafari-levi" },
  { path: "/opas/esteetton-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-esteetton-levi" },
  { path: "/guide/accessible-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-esteetton-levi" },
  { path: "/guide/apres-ski-and-nightlife-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-afterski-ja-yoelama-levilla" },
  { path: "/opas/jouluillallinen-levilla", lang: "fi", priority: 0.7, changefreq: "monthly" },
  { path: "/opas/paivaretket-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-paivaretket-levilla" },
  { path: "/guide/day-trips-from-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-paivaretket-levilla" },
  { path: "/opas/valinevuokraus-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-valinevuokraus-levilla" },
  { path: "/guide/equipment-rental-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-valinevuokraus-levilla" },
  { path: "/opas/tapahtumat-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-tapahtumat-levilla" },
  { path: "/guide/events-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-tapahtumat-levilla" },
  { path: "/opas/uusivuosi-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-uusivuosi-levilla" },
  { path: "/guide/new-years-eve-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-uusivuosi-levilla" },
  { path: "/guide/packing-list-for-lapland", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-pakkauslista-lapin-lomalle" },
  { path: "/opas/romanttinen-loma-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-romanttinen-loma-levilla" },
  { path: "/guide/romantic-getaway-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-romanttinen-loma-levilla" },
  { path: "/opas/saamelaiset-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-saamelaiset-levilla" },
  { path: "/guide/sami-culture-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-saamelaiset-levilla" },
  { path: "/guide/santa-claus-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-joulupukki-levilla" },
  { path: "/opas/hiihtoloma-levilla", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-hiihtoloma-levilla" },
  { path: "/guide/ski-holiday-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-hiihtoloma-levilla" },
  { path: "/opas/kevatlaskettelu-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevatlaskettelu-levi" },
  { path: "/guide/spring-skiing-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevatlaskettelu-levi" },
  { path: "/de/ratgeber/fruehlings-skifahren-levi", lang: "de", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevatlaskettelu-levi" },
  { path: "/sv/guide/varskidakning-levi", lang: "sv", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevatlaskettelu-levi" },
  { path: "/es/guia/esqui-primavera-levi", lang: "es", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevatlaskettelu-levi" },
  { path: "/fr/guide/ski-printemps-levi", lang: "fr", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevatlaskettelu-levi" },
  { path: "/nl/gids/lente-skieen-levi", lang: "nl", priority: 0.7, changefreq: "monthly", altGroup: "opas-kevatlaskettelu-levi" },
  { path: "/opas/levi-tammikuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-january" },
  { path: "/guide/levi-in-january", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-january" },
  { path: "/opas/levi-helmikuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-february" },
  { path: "/guide/levi-in-february", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-february" },
  { path: "/opas/levi-maaliskuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-march" },
  { path: "/guide/levi-in-march", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-march" },
  { path: "/opas/levi-huhtikuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-april" },
  { path: "/guide/levi-in-april", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-april" },
  { path: "/opas/levi-toukokuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-may" },
  { path: "/guide/levi-in-may", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-may" },
  { path: "/opas/levi-kesakuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-june" },
  { path: "/guide/levi-in-june", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-june" },
  { path: "/opas/levi-heinakuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-july" },
  { path: "/guide/levi-in-july", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-july" },
  { path: "/opas/levi-elokuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-august" },
  { path: "/guide/levi-in-august", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-august" },
  { path: "/opas/levi-syyskuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-september" },
  { path: "/guide/levi-in-september", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-september" },
  { path: "/opas/levi-lokakuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-october" },
  { path: "/guide/levi-in-october", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-october" },
  { path: "/opas/levi-marraskuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-november" },
  { path: "/guide/levi-in-november", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-november" },
  { path: "/opas/levi-joulukuussa", lang: "fi", priority: 0.6, changefreq: "monthly", altGroup: "levi-december" },
  { path: "/guide/levi-in-december", lang: "en", priority: 0.6, changefreq: "monthly", altGroup: "levi-december" },
  { path: "/opas/mokki-vai-huoneisto-levi", lang: "fi", priority: 0.7, changefreq: "monthly", altGroup: "opas-mokki-vai-huoneisto-levi" },
  { path: "/guide/cabin-vs-apartment-in-levi", lang: "en", priority: 0.7, changefreq: "monthly", altGroup: "opas-mokki-vai-huoneisto-levi" },
];

export default SITEMAP_ROUTES;
